const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");

const {
    BLOCKCHAIN_RPC_URL,
    EXPECTED_NETWORK_ID
} = require("../config/blockchain");


// =========================================================
// PROVIDER
// =========================================================

const provider =
    new ethers.JsonRpcProvider(
        BLOCKCHAIN_RPC_URL
    );


// =========================================================
// DEPLOYMENT ARTIFACT
// =========================================================

const deploymentPath =
    path.join(
        __dirname,
        "../../deployment/output/LandRegistryV2.json"
    );


// The artifact will be generated by deployment.
// We intentionally fail clearly if it does not exist.

if (!fs.existsSync(deploymentPath)) {
    throw new Error(
        "LandRegistryV2 deployment artifact not found. Deploy the contract first."
    );
}


const deployment =
    JSON.parse(
        fs.readFileSync(
            deploymentPath,
            "utf8"
        )
    );


const contractAddress =
    deployment.contractAddress;

const contractAbi =
    deployment.abi;


// =========================================================
// READ-ONLY CONTRACT
// =========================================================

const contract =
    new ethers.Contract(
        contractAddress,
        contractAbi,
        provider
    );


// =========================================================
// GET GANACHE SIGNER
// =========================================================

async function getSigner(
    walletAddress
) {

    if (!walletAddress) {
        throw new Error(
            "Wallet address is required."
        );
    }

    const accounts =
        await provider.send(
            "eth_accounts",
            []
        );

    const normalizedAddress =
        walletAddress.toLowerCase();

    const matchedAccount =
        accounts.find(
            account =>
                account.toLowerCase() ===
                normalizedAddress
        );

    if (!matchedAccount) {
        throw new Error(
            `Wallet ${walletAddress} is not available on the connected Ganache network.`
        );
    }

    return provider.getSigner(
        matchedAccount
    );
}


// =========================================================
// GET WRITABLE CONTRACT
// =========================================================

async function getWritableContract(
    walletAddress
) {

    const signer =
        await getSigner(
            walletAddress
        );

    return contract.connect(
        signer
    );
}


// =========================================================
// BLOCKCHAIN STATUS
// =========================================================

async function getBlockchainStatus() {

    const network =
        await provider.getNetwork();

    const blockNumber =
        await provider.getBlockNumber();

    const accounts =
        await provider.send(
            "eth_accounts",
            []
        );

    return {

        rpcUrl:
            BLOCKCHAIN_RPC_URL,

        chainId:
            network.chainId.toString(),

        configuredNetworkId:
            EXPECTED_NETWORK_ID,

        blockNumber,

        accountCount:
            accounts.length,

        accounts,

        contractAddress

    };
}


// =========================================================
// CONTRACT INFO
// =========================================================

async function getContractInfo() {

    const network =
        await provider.getNetwork();

    const blockNumber =
        await provider.getBlockNumber();

    return {

        contractName:
            deployment.contractName,

        contractAddress,

        chainId:
            network.chainId.toString(),

        configuredNetworkId:
            EXPECTED_NETWORK_ID,

        blockNumber,

        deployerAddress:
            deployment.deployerAddress,

        deployedAt:
            deployment.deployedAt

    };
}


// =========================================================
// READ: USER ROLE
// =========================================================

async function getBlockchainRole(
    walletAddress
) {

    const result =
        await contract.getRole(
            walletAddress
        );

    return {

        role:
            Number(result[0]),

        regionId:
            result[1]

    };
}


// =========================================================
// READ: OFFICER REGION
// =========================================================

async function getOfficerRegion(
    walletAddress
) {

    return contract.getOfficerRegion(
        walletAddress
    );
}


// =========================================================
// READ: LAND
// =========================================================

async function getBlockchainLand(
    landId
) {

    return contract.getLand(
        landId
    );
}


// =========================================================
// READ: TRANSFER
// =========================================================

async function getBlockchainTransfer(
    transferId
) {

    return contract.getTransfer(
        transferId
    );
}


// =========================================================
// READ: LAND UPDATE
// =========================================================

async function getBlockchainLandUpdate(
    requestId
) {

    return contract.getLandUpdate(
        requestId
    );
}


// =========================================================
// READ: DOCUMENT
// =========================================================

async function getBlockchainDocument(
    documentId
) {

    return contract.getDocument(
        documentId
    );
}


// =========================================================
// WRITE: ASSIGN SUPERVISOR
// =========================================================

async function assignSupervisor(
    walletAddress
) {

    const writableContract =
        await getWritableContract(
            walletAddress
        );

    const tx =
        await writableContract.assignSupervisor(
            walletAddress
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        walletAddress

    };
}


// =========================================================
// WRITE: ASSIGN OFFICER
// =========================================================

async function assignOfficer(
    supervisorWallet,
    officerWallet,
    regionId
) {

    const writableContract =
        await getWritableContract(
            supervisorWallet
        );

    const tx =
        await writableContract.assignOfficer(
            officerWallet,
            regionId
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        walletAddress:
            officerWallet,

        regionId

    };
}


// =========================================================
// WRITE: ASSIGN CITIZEN
// =========================================================

async function assignCitizen(
    supervisorWallet,
    citizenWallet
) {

    const writableContract =
        await getWritableContract(
            supervisorWallet
        );

    const tx =
        await writableContract.assignCitizen(
            citizenWallet
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        walletAddress:
            citizenWallet

    };
}


// =========================================================
// WRITE: REGISTER LAND
// =========================================================

async function registerLand(
    officerWallet,
    landId,
    surveyNumber,
    parcelArea,
    areaUnit,
    location,
    landUseType,
    zone,
    regionId
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.registerLand(
            landId,
            surveyNumber,
            parcelArea,
            areaUnit,
            location,
            landUseType,
            zone,
            regionId
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        landId,

        surveyNumber,

        regionId

    };
}


// =========================================================
// WRITE: ALLOCATE LAND
// =========================================================

async function allocateLand(
    officerWallet,
    landId,
    citizenAddress
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.allocateLand(
            landId,
            citizenAddress
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        landId,

        citizenAddress

    };
}


// =========================================================
// WRITE: PROPOSE TRANSFER
// =========================================================

async function proposeTransfer(
    sellerWallet,
    transferId,
    landId,
    buyerAddress,
    reason = ""
) {

    const writableContract =
        await getWritableContract(
            sellerWallet
        );

    const tx =
        await writableContract.proposeTransfer(
            transferId,
            landId,
            buyerAddress,
            reason
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        transferId,

        landId,

        buyerAddress,

        reason

    };
}


// =========================================================
// WRITE: ACCEPT TRANSFER
// =========================================================

async function acceptTransfer(
    buyerWallet,
    transferId
) {

    const writableContract =
        await getWritableContract(
            buyerWallet
        );

    const tx =
        await writableContract.acceptTransfer(
            transferId
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        transferId

    };
}


// =========================================================
// WRITE: APPROVE TRANSFER
// =========================================================

async function approveTransfer(
    officerWallet,
    transferId
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.approveTransfer(
            transferId
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        transferId

    };
}


// =========================================================
// WRITE: REJECT TRANSFER
// =========================================================

async function rejectTransfer(
    officerWallet,
    transferId,
    reason
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.rejectTransfer(
            transferId,
            reason || ""
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        transferId,

        reason:
            reason || ""

    };
}


// =========================================================
// WRITE: PROPOSE LAND UPDATE
// =========================================================

async function proposeLandUpdate(
    citizenWallet,
    requestId,
    landId,
    updateType,
    requestedArea,
    requestedAreaUnit,
    requestedLandUse,
    requestedLandType,
    reason
) {

    const writableContract =
        await getWritableContract(
            citizenWallet
        );

    const tx =
        await writableContract.proposeLandUpdate(
            requestId,
            landId,
            updateType,
            requestedArea || 0,
            requestedAreaUnit || "",
            requestedLandUse || "",
            requestedLandType || "",
            reason || ""
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        requestId,

        landId,

        updateType

    };
}


// =========================================================
// WRITE: APPROVE LAND UPDATE
// =========================================================

async function approveLandUpdate(
    officerWallet,
    requestId
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.approveLandUpdate(
            requestId
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        requestId

    };
}


// =========================================================
// WRITE: REJECT LAND UPDATE
// =========================================================

async function rejectLandUpdate(
    officerWallet,
    requestId,
    reason
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.rejectLandUpdate(
            requestId,
            reason || ""
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        requestId,

        reason:
            reason || ""

    };
}


// =========================================================
// WRITE: ANCHOR DOCUMENT
// =========================================================

async function anchorDocument(
    officerWallet,
    documentId,
    landId,
    transactionId,
    documentType,
    sha256Hash,
    ipfsCid
) {

    const writableContract =
        await getWritableContract(
            officerWallet
        );

    const tx =
        await writableContract.anchorDocument(
            documentId,
            landId,
            transactionId,
            documentType,
            sha256Hash,
            ipfsCid
        );

    const receipt =
        await tx.wait();

    return {

        transactionHash:
            receipt.hash,

        documentId,

        landId,

        transactionId,

        documentType,

        sha256Hash,

        ipfsCid

    };
}


// =========================================================
// EXPORTS
// =========================================================

module.exports = {

    provider,

    contract,

    contractAddress,

    contractAbi,

    getSigner,

    getWritableContract,

    getBlockchainStatus,

    getContractInfo,

    getBlockchainRole,

    getOfficerRegion,

    getBlockchainLand,

    getBlockchainTransfer,

    getBlockchainLandUpdate,

    getBlockchainDocument,

    assignSupervisor,

    assignOfficer,

    assignCitizen,

    registerLand,

    allocateLand,

    proposeTransfer,

    acceptTransfer,

    approveTransfer,

    rejectTransfer,

    proposeLandUpdate,

    approveLandUpdate,

    rejectLandUpdate,

    anchorDocument

};